web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 10

tasks:
  check_brokenstones_freeleech:
    rss:
      url: (brokenstones RSS URL)
      # Need to keep comments field from RSS for brokenstones_lookup
      other_fields: [comments]
    brokenstones_lookup:
      username: (username)
      password: (password)
    if2:
      - 'not freeleech': reject
      - 'content_size >= 5000000000': reject
      # There's probably a better way of doing this, but this will leave entries where
      # the lookup failed as undecided while accepting/rejecting everything else.
      - 'freeleech and content_size < 5000000000': accept
