web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 60

tasks:
  check_brokenstones_freeleech:
    rss:
      url: (brokenstones RSS URL)
      other_fields: [comments]
    brokenstones_lookup:
      username: (username)
      password: (password)
    if2:
      - 'not freeleech': reject
      - 'content_size >= 5000000000': reject
      - 'freeleech and content_size < 5000000000': accept
