web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 30

variables: secrets.yml
tasks:
  check_brokenstones_freeleech:
    rss:
      url: '{? brokenstones.rss_url ?}'
      # Need to keep comments field from RSS for brokenstones_lookup
      other_fields: [comments]
    brokenstones_lookup:
      username: '{? brokenstones.username ?}'
      password: '{? brokenstones.password ?}'
    if2:
      - 'not freeleech': reject
      - 'content_size >= 5000': reject
      # There's probably a better way of doing this, but this will leave entries where
      # the lookup failed as undecided while accepting/rejecting everything else.
      - 'freeleech and content_size < 5000': accept
    notify:
      entries:
        title: 'New BrokenStones freeleech'
        message: '{{title}} ({{content_size}} MB, {{snatches}} snatches, {{seeders}} seeds, {{leechers}} leeches)'
        via:
          - pushover:
              user_key: '{? pushover.user_key ?}'
              url: '{{comments}}'
      abort:
        title: 'Flexget task aborted'
        via:
          - pushover:
              user_key: '{? pushover.user_key ?}'
    qbittorrent:
      host: bassanio.lan
      port: 8080
      username: '{? qbittorrent.username ?}'
      password: '{? qbittorrent.password ?}'
      label: flexget
